In [19]:
import numpy as np

## DataTypes & Attributes

In [20]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [21]:
type(a1)

numpy.ndarray

In [22]:
a2 = np.array([
  [1, 2.0, 3.3],
  [4, 5, 6.5],
])

a3 = np.array([
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ],
  [
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18],
  ]
])

In [23]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [17]:
a3.shape

(2, 3, 3)

In [ ]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [29]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [30]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

#### Create a DataFrame from a NumPy array

In [31]:
import pandas as pd

In [40]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [41]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [42]:
sample_array.dtype

dtype('int64')

In [ ]:
ones = np.ones((2, 3), dtype=int)
ones

In [53]:
type(ones)

numpy.ndarray

In [59]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
zeros.dtype

dtype('float64')

In [61]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [69]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 3, 3, 8, 7],
       [6, 1, 9, 4, 2],
       [0, 7, 2, 0, 4]])

In [70]:
random_array.size

15

In [71]:
random_array.shape

(3, 5)

In [76]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.6202611 , 0.22809253, 0.60346771],
       [0.62389816, 0.77012806, 0.40137877],
       [0.8799669 , 0.05163656, 0.42692899],
       [0.4127744 , 0.16309098, 0.63370219],
       [0.88681767, 0.4755985 , 0.91097247]])

In [77]:
random_array_2.shape

(5, 3)

In [ ]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.95601869, 0.76950448, 0.04185009],
       [0.20557624, 0.57073532, 0.92363377],
       [0.62847083, 0.82426831, 0.16614219],
       [0.1341104 , 0.97394391, 0.69912792],
       [0.71863571, 0.07713696, 0.83317001]])

In [75]:
random_array_3.shape

(5, 3)

In [78]:
# Pseudo-random numbers
np.random.seed()