In [19]:
import numpy as np

## DataTypes & Attributes

In [20]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [80]:
type(a1)

numpy.ndarray

In [81]:
a2 = np.array([
  [1, 2.0, 3.3],
  [4, 5, 6.5],
])

a3 = np.array([
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ],
  [
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18],
  ]
])

In [82]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [17]:
a3.shape

(2, 3, 3)

In [ ]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [29]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [30]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

#### Create a DataFrame from a NumPy array

In [84]:
import pandas as pd

In [85]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [41]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [42]:
sample_array.dtype

dtype('int64')

In [86]:
ones = np.ones((2, 3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
type(ones)

numpy.ndarray

In [59]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
zeros.dtype

dtype('float64')

In [61]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [69]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 3, 3, 8, 7],
       [6, 1, 9, 4, 2],
       [0, 7, 2, 0, 4]])

In [70]:
random_array.size

15

In [71]:
random_array.shape

(3, 5)

In [76]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.6202611 , 0.22809253, 0.60346771],
       [0.62389816, 0.77012806, 0.40137877],
       [0.8799669 , 0.05163656, 0.42692899],
       [0.4127744 , 0.16309098, 0.63370219],
       [0.88681767, 0.4755985 , 0.91097247]])

In [77]:
random_array_2.shape

(5, 3)

In [88]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.25076223, 0.75673604, 0.26745473],
       [0.07471854, 0.43887835, 0.57056404],
       [0.86975147, 0.7851743 , 0.60893205],
       [0.52481532, 0.49190686, 0.78476279],
       [0.7899052 , 0.38103177, 0.18371897]])

In [75]:
random_array_3.shape

(5, 3)

In [97]:
# Pseudo-random numbers
np.random.seed(999) # keep random but sync with this seed
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 5, 1],
       [8, 1, 9],
       [3, 0, 5],
       [8, 8, 0],
       [5, 2, 5]])

In [90]:
random_array_4.shape

(5, 3)

In [105]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [108]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [109]:
# seed makes random but controllable to be able to repeat same on another notebook, another machine

## 3. Viewing Arrays and Matrices

In [113]:
random_array_4

array([[0, 5, 1],
       [8, 1, 9],
       [3, 0, 5],
       [8, 8, 0],
       [5, 2, 5]])

In [112]:
np.unique(random_array_4)

array([0, 1, 2, 3, 5, 8, 9])

In [114]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [116]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
a2.shape

(2, 3)

In [ ]:
a2[0]

array([1. , 2. , 3.3])

In [121]:
a3.shape

(2, 3, 3)

In [122]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [120]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [124]:
a2[1]

array([4. , 5. , 6.5])

In [125]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [131]:
# first values of each row column of an array
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [133]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [134]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [135]:
a4.shape

(2, 3, 4, 5)

In [136]:
a4.ndim

4

In [141]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

In [147]:
a4[:,:,:,:1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## Manipulating & comparing arrays

### Arithmetic

In [148]:
a1

array([1, 2, 3])

In [149]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [150]:
a1 + ones

array([2., 3., 4.])

In [151]:
a1 - ones

array([0., 1., 2.])

In [152]:
a1 * ones

array([1., 2., 3.])

In [155]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [154]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [156]:
a2, a3

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [162]:
# will throw error, but how to reshape to be compatibile sizes ?
# google how to reshape numpy array
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [189]:
a2.shape, a3.shape
# there are methods to reshape, np.reshape(), discover how this actually works..

((2, 3), (2, 3, 3))

In [176]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [ ]:
a1 / ones

array([1., 2., 3.])

In [177]:
# floor division removes decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [178]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [180]:
a2, a2 ** 2

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 42.25]]))

In [181]:
# same as
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [182]:
# same
np.add(a1, ones), a1 + ones

(array([2., 3., 4.]), array([2., 3., 4.]))

In [183]:
a1 / 2

array([0.5, 1. , 1.5])

In [186]:
a2, np.mod(a2, 2), a2 % 2

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[1. , 0. , 1.3],
        [0. , 1. , 0.5]]),
 array([[1. , 0. , 1.3],
        [0. , 1. , 0.5]]))

In [187]:
a1, np.exp(a1)

(array([1, 2, 3]), array([ 2.71828183,  7.3890561 , 20.08553692]))

In [188]:
a1, np.log(a1)

(array([1, 2, 3]), array([0.        , 0.69314718, 1.09861229]))

## Aggregation

Performing same operation on a number of things

In [190]:
listy_list = [1, 2, 3]

In [191]:
type(listy_list)

list

In [192]:
sum(listy_list)

6

In [193]:
# numpy has own version of these
a1

array([1, 2, 3])

In [194]:
sum(a1)

np.int64(6)

In [195]:
np.sum(a1)

np.int64(6)

Use pythongs sum() and numpys on sum()

In [196]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [198]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [201]:
%timeit sum(massive_array) # python sum
%timeit np.sum(massive_array) # np sum

2.73 ms ± 17.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.4 μs ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
