# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
one = np.array([1, 2, 3])


# Create a 2-dimensional NumPy array using np.array()
two = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

# Create a 3-dimensional Numpy array using np.array()
three = np.array([
  [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
  ], 
  [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
  ], 
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one.shape, one.ndim, one.dtype, one.size, type(one)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
two.shape, two.ndim, two.dtype, two.size, type(type)


((3, 3), 2, dtype('int64'), 9, type)

In [8]:
# Attributes of 3-dimensional array
three.shape, three.ndim, three.dtype, three.size, type(three)


((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(two)
df


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [13]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
arange = np.arange(0, 100, 3)
arange


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))
random_array

array([[1, 4],
       [0, 0],
       [9, 7],
       [6, 1],
       [0, 0],
       [8, 9],
       [0, 1]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_floats = np.random.random(size=(3, 5))
random_floats


array([[0.84772231, 0.73200285, 0.42769523, 0.44398124, 0.84290419],
       [0.49871821, 0.49210632, 0.91360999, 0.14617453, 0.07965403],
       [0.69565329, 0.4019357 , 0.03968558, 0.84932237, 0.20295408]])

In [25]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, size=(4, 6))


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [31]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numbers = np.random.randint(1, 10, size=(3, 7))
random_numbers

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6],
       [2, 9, 5, 6, 4, 7, 9]])

In [32]:
# Find the unique numbers in the array you just created
np.unique(random_numbers)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [33]:
# Find the 0'th index of the latest array you created
random_numbers[0]

array([7, 9, 3, 7, 1, 4, 4])

In [35]:
# Get the first 2 rows of latest array you created
random_numbers[:2]

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
random_numbers[:2, :2]

array([[7, 9],
       [5, 7]])

In [40]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_numbers2 = np.random.randint(0, 10, size=(3, 5))
random_numbers2

array([[0, 8, 8, 3, 8],
       [2, 6, 5, 7, 8],
       [4, 0, 2, 9, 7]])

In [43]:
ones2 = np.ones((3, 5))
ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
# Add the two arrays together
random_numbers2 + ones2

array([[ 1.,  9.,  9.,  4.,  9.],
       [ 3.,  7.,  6.,  8.,  9.],
       [ 5.,  1.,  3., 10.,  8.]])

In [47]:
# Create another array of ones of shape (5, 3)
another_array = np.ones(shape=(5, 3))
another_array


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# Try add the array of ones and the other most recent array together
ones2 + random_numbers2

array([[ 1.,  9.,  9.,  4.,  9.],
       [ 3.,  7.,  6.,  8.,  9.],
       [ 5.,  1.,  3., 10.,  8.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [51]:
# Create another array of ones of shape (3, 5)
ones3 = np.ones(shape=(3, 5))
ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# Subtract the new array of ones from the other most recent array
random_numbers2 - ones3

array([[-1.,  7.,  7.,  2.,  7.],
       [ 1.,  5.,  4.,  6.,  7.],
       [ 3., -1.,  1.,  8.,  6.]])

In [ ]:
# Multiply the ones array with the latest array
ones3 * random_numbers2

array([[0., 8., 8., 3., 8.],
       [2., 6., 5., 7., 8.],
       [4., 0., 2., 9., 7.]])

In [56]:
np.multiply(ones3, random_numbers2)

array([[0., 8., 8., 3., 8.],
       [2., 6., 5., 7., 8.],
       [4., 0., 2., 9., 7.]])

In [57]:
# Take the latest array to the power of 2 using '**'
random_numbers2 ** 2


array([[ 0, 64, 64,  9, 64],
       [ 4, 36, 25, 49, 64],
       [16,  0,  4, 81, 49]])

In [58]:
# Do the same thing with np.square()
np.square(random_numbers2)


array([[ 0, 64, 64,  9, 64],
       [ 4, 36, 25, 49, 64],
       [16,  0,  4, 81, 49]])

In [59]:
# Find the mean of the latest array using np.mean()
random_numbers2.mean()

np.float64(5.133333333333334)

In [60]:
# Find the maximum of the latest array using np.max()
random_numbers2.max()

np.int64(9)

In [61]:
# Find the minimum of the latest array using np.min()
random_numbers2.min()

np.int64(0)

In [62]:
# Find the standard deviation of the latest array
random_numbers2.std()

np.float64(2.985892756874492)

In [63]:
# Find the variance of the latest array
random_numbers2.var()

np.float64(8.915555555555555)

In [65]:
# Reshape the latest array to (3, 5, 1)
random_numbers2.reshape((3, 5, 1))


array([[[0],
        [8],
        [8],
        [3],
        [8]],

       [[2],
        [6],
        [5],
        [7],
        [8]],

       [[4],
        [0],
        [2],
        [9],
        [7]]])

In [67]:
random_numbers2

array([[0, 8, 8, 3, 8],
       [2, 6, 5, 7, 8],
       [4, 0, 2, 9, 7]])

In [66]:
# Transpose the latest array
random_numbers2.T

array([[0, 2, 4],
       [8, 6, 0],
       [8, 5, 2],
       [3, 7, 9],
       [8, 8, 7]])

What does the transpose do?

In [70]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0, 10, size=(3, 3))
arr2 = np.random.randint(0, 10, size=(3, 2))

In [71]:
arr1, arr2

(array([[1, 2, 0],
        [4, 0, 7],
        [0, 0, 1]]),
 array([[1, 5],
        [6, 4],
        [0, 0]]))

In [72]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

array([[13, 13],
       [ 4, 20],
       [ 0,  0]])

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(0, 10, size=(4, 3))
arr4 = np.random.randint(0, 10, size=(4, 3))

In [75]:
arr3, arr4

(array([[2, 1, 4],
        [9, 5, 6],
        [3, 6, 7],
        [0, 5, 7]]),
 array([[4, 3, 1],
        [5, 5, 0],
        [8, 5, 2],
        [3, 3, 2]]))

In [76]:
# Perform a dot product on the two newest arrays you created
arr3.dot(arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [77]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3.dot(arr4.T)

array([[ 15,  15,  29,  17],
       [ 57,  70, 109,  54],
       [ 37,  45,  68,  41],
       [ 22,  25,  39,  29]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [78]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr5 = np.random.randint(0, 10, size=(3, 5))
arr6 = np.random.randint(0, 10, size=(3, 5))

In [79]:
arr5, arr6

(array([[9, 2, 2, 3, 6],
        [3, 8, 0, 7, 6],
        [1, 7, 0, 8, 8]]),
 array([[1, 6, 9, 2, 6],
        [9, 8, 3, 0, 1],
        [0, 4, 4, 6, 8]]))

In [80]:
# Compare the two arrays with '>'
arr5 > arr6


array([[ True, False, False,  True, False],
       [False, False, False,  True,  True],
       [ True,  True, False,  True, False]])

What happens when you compare the arrays with `>`?

In [81]:
# Compare the two arrays with '>='
arr6 >= arr5

array([[False,  True,  True, False,  True],
       [ True,  True,  True, False, False],
       [False, False,  True, False,  True]])

In [83]:
arr6

array([[1, 6, 9, 2, 6],
       [9, 8, 3, 0, 1],
       [0, 4, 4, 6, 8]])

In [ ]:
# Find which elements of the first array are greater than 7
arr6 > 7

array([[False, False,  True, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False,  True]])

In [86]:
# Which parts of each array are equal? (try using '==')
arr5 == arr6

array([[False, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False,  True]])

In [88]:
# Sort one of the arrays you just created in ascending order
arr5.sort(axis=1)
arr5

array([[2, 2, 3, 6, 9],
       [0, 3, 6, 7, 8],
       [0, 1, 7, 8, 8]])

In [89]:
# Sort the indexes of one of the arrays you just created
arr5.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [90]:
# Find the index with the maximum value in one of the arrays you've created
arr5.argmin()

np.int64(5)

In [91]:
# Find the index with the minimum value in one of the arrays you've created
arr5.argmax()


np.int64(4)

In [93]:
arr5

array([[2, 2, 3, 6, 9],
       [0, 3, 6, 7, 8],
       [0, 1, 7, 8, 8]])

In [92]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
arr5.argmax(axis=1)


array([4, 4, 3])

In [94]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
arr5.argmin(axis=0)


array([1, 2, 0, 0, 1])

In [97]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)


array([[ 0.1087118 ,  0.10576365,  0.92066672, -0.22672246,  0.65304831],
       [ 1.10268747, -1.84980294,  1.16863124, -0.9853818 , -1.09394041],
       [-2.87945689, -0.80317767, -0.00485694, -0.38332331, -0.46252686]])

In [99]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.